<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => '1',
                'data_type_id' => '1',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'data_type_id' => '1',
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Author',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '',
                'order' => '2',
            ),
            2 => 
            array (
                'id' => '3',
                'data_type_id' => '1',
                'field' => 'category_id',
                'type' => 'text',
                'display_name' => 'Category',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '',
                'order' => '3',
            ),
            3 => 
            array (
                'id' => '4',
                'data_type_id' => '1',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '4',
            ),
            4 => 
            array (
                'id' => '5',
                'data_type_id' => '1',
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'excerpt',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '5',
            ),
            5 => 
            array (
                'id' => '6',
                'data_type_id' => '1',
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Body',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '6',
            ),
            6 => 
            array (
                'id' => '7',
                'data_type_id' => '1',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Post Image',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => '7',
            ),
            7 => 
            array (
                'id' => '8',
                'data_type_id' => '1',
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'slug',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"slugify":{"origin":"title","forceUpdate":true}}',
                'order' => '8',
            ),
            8 => 
            array (
                'id' => '9',
                'data_type_id' => '1',
                'field' => 'meta_description',
                'type' => 'text_area',
                'display_name' => 'meta_description',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '9',
            ),
            9 => 
            array (
                'id' => '10',
                'data_type_id' => '1',
                'field' => 'meta_keywords',
                'type' => 'text_area',
                'display_name' => 'meta_keywords',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '10',
            ),
            10 => 
            array (
                'id' => '11',
                'data_type_id' => '1',
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'order' => '11',
            ),
            11 => 
            array (
                'id' => '12',
                'data_type_id' => '1',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '12',
            ),
            12 => 
            array (
                'id' => '13',
                'data_type_id' => '1',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '13',
            ),
            13 => 
            array (
                'id' => '14',
                'data_type_id' => '2',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '1',
            ),
            14 => 
            array (
                'id' => '15',
                'data_type_id' => '2',
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'author_id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '2',
            ),
            15 => 
            array (
                'id' => '16',
                'data_type_id' => '2',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '3',
            ),
            16 => 
            array (
                'id' => '17',
                'data_type_id' => '2',
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'excerpt',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '4',
            ),
            17 => 
            array (
                'id' => '18',
                'data_type_id' => '2',
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'body',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '5',
            ),
            18 => 
            array (
                'id' => '19',
                'data_type_id' => '2',
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'slug',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"slugify":{"origin":"title"}}',
                'order' => '6',
            ),
            19 => 
            array (
                'id' => '20',
                'data_type_id' => '2',
                'field' => 'meta_description',
                'type' => 'text',
                'display_name' => 'meta_description',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '7',
            ),
            20 => 
            array (
                'id' => '21',
                'data_type_id' => '2',
                'field' => 'meta_keywords',
                'type' => 'text',
                'display_name' => 'meta_keywords',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '8',
            ),
            21 => 
            array (
                'id' => '22',
                'data_type_id' => '2',
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":"INACTIVE","options":{"INACTIVE":"INACTIVE","ACTIVE":"ACTIVE"}}',
                'order' => '9',
            ),
            22 => 
            array (
                'id' => '23',
                'data_type_id' => '2',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '10',
            ),
            23 => 
            array (
                'id' => '24',
                'data_type_id' => '2',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '11',
            ),
            24 => 
            array (
                'id' => '25',
                'data_type_id' => '2',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'image',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '12',
            ),
            25 => 
            array (
                'id' => '26',
                'data_type_id' => '3',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '1',
            ),
            26 => 
            array (
                'id' => '27',
                'data_type_id' => '3',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '2',
            ),
            27 => 
            array (
                'id' => '28',
                'data_type_id' => '3',
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'email',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '3',
            ),
            28 => 
            array (
                'id' => '29',
                'data_type_id' => '3',
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'password',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '',
                'order' => '4',
            ),
            29 => 
            array (
                'id' => '30',
                'data_type_id' => '3',
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"roles","pivot":"0"}',
                'order' => '10',
            ),
            30 => 
            array (
                'id' => '31',
                'data_type_id' => '3',
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'remember_token',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '5',
            ),
            31 => 
            array (
                'id' => '32',
                'data_type_id' => '3',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '6',
            ),
            32 => 
            array (
                'id' => '33',
                'data_type_id' => '3',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '7',
            ),
            33 => 
            array (
                'id' => '34',
                'data_type_id' => '3',
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'avatar',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '8',
            ),
            34 => 
            array (
                'id' => '35',
                'data_type_id' => '5',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '1',
            ),
            35 => 
            array (
                'id' => '36',
                'data_type_id' => '5',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '2',
            ),
            36 => 
            array (
                'id' => '37',
                'data_type_id' => '5',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '3',
            ),
            37 => 
            array (
                'id' => '38',
                'data_type_id' => '5',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '4',
            ),
            38 => 
            array (
                'id' => '39',
                'data_type_id' => '4',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '1',
            ),
            39 => 
            array (
                'id' => '40',
                'data_type_id' => '4',
                'field' => 'parent_id',
                'type' => 'select_dropdown',
                'display_name' => 'parent_id',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":"","null":"","options":{"":"-- None --"},"relationship":{"key":"id","label":"name"}}',
                'order' => '2',
            ),
            40 => 
            array (
                'id' => '41',
                'data_type_id' => '4',
                'field' => 'order',
                'type' => 'text',
                'display_name' => 'order',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":1}',
                'order' => '3',
            ),
            41 => 
            array (
                'id' => '42',
                'data_type_id' => '4',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '4',
            ),
            42 => 
            array (
                'id' => '43',
                'data_type_id' => '4',
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'slug',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"slugify":{"origin":"name"}}',
                'order' => '5',
            ),
            43 => 
            array (
                'id' => '44',
                'data_type_id' => '4',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '6',
            ),
            44 => 
            array (
                'id' => '45',
                'data_type_id' => '4',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '7',
            ),
            45 => 
            array (
                'id' => '46',
                'data_type_id' => '6',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '1',
            ),
            46 => 
            array (
                'id' => '47',
                'data_type_id' => '6',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '2',
            ),
            47 => 
            array (
                'id' => '48',
                'data_type_id' => '6',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '3',
            ),
            48 => 
            array (
                'id' => '49',
                'data_type_id' => '6',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '',
                'order' => '4',
            ),
            49 => 
            array (
                'id' => '50',
                'data_type_id' => '6',
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '5',
            ),
        ));
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => '51',
                'data_type_id' => '1',
                'field' => 'seo_title',
                'type' => 'text',
                'display_name' => 'seo_title',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '14',
            ),
            1 => 
            array (
                'id' => '52',
                'data_type_id' => '1',
                'field' => 'featured',
                'type' => 'checkbox',
                'display_name' => 'featured',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '15',
            ),
            2 => 
            array (
                'id' => '53',
                'data_type_id' => '3',
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'role_id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '',
                'order' => '9',
            ),
            3 => 
            array (
                'id' => '54',
                'data_type_id' => '7',
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            4 => 
            array (
                'id' => '55',
                'data_type_id' => '7',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            5 => 
            array (
                'id' => '56',
                'data_type_id' => '7',
                'field' => 'subtitle',
                'type' => 'text',
                'display_name' => 'Subtitle',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            6 => 
            array (
                'id' => '57',
                'data_type_id' => '7',
                'field' => 'content',
                'type' => 'text_area',
                'display_name' => 'Content',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            7 => 
            array (
                'id' => '58',
                'data_type_id' => '7',
                'field' => 'fade_direction',
                'type' => 'text',
                'display_name' => 'Fade Direction',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            8 => 
            array (
                'id' => '59',
                'data_type_id' => '7',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Image',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            9 => 
            array (
                'id' => '60',
                'data_type_id' => '7',
                'field' => 'image_alt',
                'type' => 'text',
                'display_name' => 'Image Alt',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
            10 => 
            array (
                'id' => '61',
                'data_type_id' => '7',
                'field' => 'image_position',
                'type' => 'text',
                'display_name' => 'Image Position',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '8',
            ),
            11 => 
            array (
                'id' => '62',
                'data_type_id' => '7',
                'field' => 'display',
                'type' => 'checkbox',
                'display_name' => 'Display',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '9',
            ),
            12 => 
            array (
                'id' => '63',
                'data_type_id' => '7',
                'field' => 'order',
                'type' => 'number',
                'display_name' => 'Order',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '10',
            ),
            13 => 
            array (
                'id' => '64',
                'data_type_id' => '7',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '11',
            ),
            14 => 
            array (
                'id' => '65',
                'data_type_id' => '7',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '12',
            ),
            15 => 
            array (
                'id' => '66',
                'data_type_id' => '8',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '1',
            ),
            16 => 
            array (
                'id' => '67',
                'data_type_id' => '8',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            17 => 
            array (
                'id' => '68',
                'data_type_id' => '8',
                'field' => 'content',
                'type' => 'text_area',
                'display_name' => 'Content',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            18 => 
            array (
                'id' => '69',
                'data_type_id' => '8',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Image',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            19 => 
            array (
                'id' => '70',
                'data_type_id' => '8',
                'field' => 'display',
                'type' => 'checkbox',
                'display_name' => 'Display',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            20 => 
            array (
                'id' => '71',
                'data_type_id' => '8',
                'field' => 'order',
                'type' => 'number',
                'display_name' => 'Order',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            21 => 
            array (
                'id' => '72',
                'data_type_id' => '8',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
            22 => 
            array (
                'id' => '73',
                'data_type_id' => '8',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '8',
            ),
            23 => 
            array (
                'id' => '74',
                'data_type_id' => '9',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '1',
            ),
            24 => 
            array (
                'id' => '75',
                'data_type_id' => '9',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            25 => 
            array (
                'id' => '76',
                'data_type_id' => '9',
                'field' => 'description',
                'type' => 'text_area',
                'display_name' => 'Description',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            26 => 
            array (
                'id' => '77',
                'data_type_id' => '9',
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            27 => 
            array (
                'id' => '78',
                'data_type_id' => '9',
                'field' => 'link',
                'type' => 'text',
                'display_name' => 'Link',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            28 => 
            array (
                'id' => '79',
                'data_type_id' => '9',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Image',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            29 => 
            array (
                'id' => '80',
                'data_type_id' => '9',
                'field' => 'role',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
            30 => 
            array (
                'id' => '81',
                'data_type_id' => '9',
                'field' => 'display',
                'type' => 'checkbox',
                'display_name' => 'Display',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '8',
            ),
            31 => 
            array (
                'id' => '82',
                'data_type_id' => '9',
                'field' => 'order',
                'type' => 'number',
                'display_name' => 'Order',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '9',
            ),
            32 => 
            array (
                'id' => '83',
                'data_type_id' => '9',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '10',
            ),
            33 => 
            array (
                'id' => '84',
                'data_type_id' => '9',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '11',
            ),
            34 => 
            array (
                'id' => '85',
                'data_type_id' => '10',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            35 => 
            array (
                'id' => '86',
                'data_type_id' => '10',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            36 => 
            array (
                'id' => '87',
                'data_type_id' => '10',
                'field' => 'content',
                'type' => 'text_area',
                'display_name' => 'Content',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            37 => 
            array (
                'id' => '88',
                'data_type_id' => '10',
                'field' => 'link',
                'type' => 'text',
                'display_name' => 'Link',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            38 => 
            array (
                'id' => '89',
                'data_type_id' => '10',
                'field' => 'featured',
                'type' => 'checkbox',
                'display_name' => 'Featured',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            39 => 
            array (
                'id' => '90',
                'data_type_id' => '10',
                'field' => 'display',
                'type' => 'checkbox',
                'display_name' => 'Display',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            40 => 
            array (
                'id' => '91',
                'data_type_id' => '10',
                'field' => 'order',
                'type' => 'number',
                'display_name' => 'Order',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
            41 => 
            array (
                'id' => '92',
                'data_type_id' => '10',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '8',
            ),
            42 => 
            array (
                'id' => '93',
                'data_type_id' => '10',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '9',
            ),
            43 => 
            array (
                'id' => '94',
                'data_type_id' => '11',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            44 => 
            array (
                'id' => '95',
                'data_type_id' => '11',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            45 => 
            array (
                'id' => '96',
                'data_type_id' => '11',
                'field' => 'content',
                'type' => 'text_area',
                'display_name' => 'Content',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            46 => 
            array (
                'id' => '97',
                'data_type_id' => '11',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Image',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            47 => 
            array (
                'id' => '98',
                'data_type_id' => '11',
                'field' => 'display',
                'type' => 'checkbox',
                'display_name' => 'Display',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            48 => 
            array (
                'id' => '99',
                'data_type_id' => '11',
                'field' => 'order',
                'type' => 'number',
                'display_name' => 'Order',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            49 => 
            array (
                'id' => '100',
                'data_type_id' => '11',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '7',
            ),
        ));
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => '101',
                'data_type_id' => '11',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '8',
            ),
            1 => 
            array (
                'id' => '102',
                'data_type_id' => '12',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            2 => 
            array (
                'id' => '103',
                'data_type_id' => '12',
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            3 => 
            array (
                'id' => '104',
                'data_type_id' => '12',
                'field' => 'token',
                'type' => 'text',
                'display_name' => 'Token',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            4 => 
            array (
                'id' => '105',
                'data_type_id' => '12',
                'field' => 'verified',
                'type' => 'checkbox',
                'display_name' => 'Verified',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            5 => 
            array (
                'id' => '106',
                'data_type_id' => '12',
                'field' => 'active',
                'type' => 'checkbox',
                'display_name' => 'Active',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            6 => 
            array (
                'id' => '107',
                'data_type_id' => '12',
                'field' => 'ip',
                'type' => 'text',
                'display_name' => 'Ip',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            7 => 
            array (
                'id' => '108',
                'data_type_id' => '12',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
            8 => 
            array (
                'id' => '109',
                'data_type_id' => '12',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '8',
            ),
            9 => 
            array (
                'id' => '110',
                'data_type_id' => '13',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            10 => 
            array (
                'id' => '111',
                'data_type_id' => '13',
                'field' => 'from',
                'type' => 'text',
                'display_name' => 'From',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            11 => 
            array (
                'id' => '112',
                'data_type_id' => '13',
                'field' => 'content',
                'type' => 'text_area',
                'display_name' => 'Content',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            12 => 
            array (
                'id' => '113',
                'data_type_id' => '13',
                'field' => 'to',
                'type' => 'text',
                'display_name' => 'To',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            13 => 
            array (
                'id' => '114',
                'data_type_id' => '13',
                'field' => 'inbox',
                'type' => 'text',
                'display_name' => 'Inbox',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            14 => 
            array (
                'id' => '115',
                'data_type_id' => '13',
                'field' => 'cc',
                'type' => 'text',
                'display_name' => 'Cc',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            15 => 
            array (
                'id' => '116',
                'data_type_id' => '13',
                'field' => 'sent',
                'type' => 'checkbox',
                'display_name' => 'Sent',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
            16 => 
            array (
                'id' => '117',
                'data_type_id' => '13',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '8',
            ),
            17 => 
            array (
                'id' => '118',
                'data_type_id' => '13',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '9',
            ),
            18 => 
            array (
                'id' => '119',
                'data_type_id' => '7',
                'field' => 'image_display',
                'type' => 'checkbox',
                'display_name' => 'Image Display',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
        ));
        
        
    }
}